### PR TITLE
Update map.jinja for CentOS support

### PR DESCRIPTION
**Pull request by rmartins90**

### CODE REVIEW

**Comment by babilen** [comment]
Ta!

**Comment by gravyboat** [comment]
Yeah this is definitely not the package name. I'm going to revert this.

**Comment by gravyboat** [comment]
I've reverted this change, @rmartins90 can you please explain your reasoning for changing this? git2u is definitely not the default git package in either RedHat or CentOS.

**Comment by rmartins90** [comment]
You're absolutely right. Sorry.

**Comment by gravyboat** [comment]
@rmartins90 No worries, just wanted to make sure we weren't missing something.

**Pull request merged**
