### PR TITLE
add git-core/ppa when configuring debian os family.

### PR DESCRIPTION
**Pull request by haydenk**
Setup to use the latest package from the Git PPA when you're using debian or ubuntu

### CODE REVIEW

**Comment by UtahDave** [comment]
thanks!

**Comment by haydenk** [comment]
Thank you! I love saltstack! My pleasure to contribute. :)

**Comment by UtahDave** [comment]
:) We really appreciate the positive feedback!  We love saltstack, too!

Thanks for helping improve Salt!

**Comment by spoage** [comment]
I know I'm late to the party here, but I don't understand why this is necessary. I could understand making it an option, but why is it the only/default behavior? Seems like it'd potentially cause more problems than it solves.

**Comment by puneetk** [comment]
@spoage send over your recommendation as a pull, we can review and pick. only goal here is backwards compatibility and configurability.

**Comment by spoage** [comment]
Understood, will do. :+1: Just wanted to make sure there wasn't some big reason before I put in the work. :)

**Pull request merged**
